### ISSUE TITLE
Response status code does not indicate success: 404 (Not Found)

### ISSUE THREAD

**Issue by make-nz** [jellyfin/jellyfin-plugin-discogs#12]
On JF 10.9.11 and 10.10.1 I get this error, when new music files are added.

[2024-11-15 07:21:31.931 +01:00] [ERR] [29] MediaBrowser.Providers.Music.ArtistMetadataService: Error in "Discogs"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
  at Jellyfin.Plugin.Discogs.DiscogsApi.Request(HttpRequestMessage request, CancellationToken cancellationToken)
  at Jellyfin.Plugin.Discogs.DiscogsApi.GetArtist(String id, CancellationToken cancellationToken)
  at Jellyfin.Plugin.Discogs.Providers.DiscogsArtistProvider.GetMetadata(ArtistInfo info, CancellationToken cancellationToken)
  at MediaBrowser.Providers.Manager.MetadataService2.ExecuteRemoteProviders(MetadataResult1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by c-esc** [comment]
I observed that when I manually add a Discogs _Album_ ID to the metadata and click on the Discogs link on the album page, it brings you to https://www.discogs.com/master/XXX where XXX is just what I put in the metadata and as far as I understand it, releases that are only 1 single album (i.e. don't have a _master_ page) go to a 404 (they should be _release_ instead of _master_). No idea if that makes sense and is related but maybe it's a lead. Cheers
