### ISSUE TITLE
Status: NotSupported on new Installation

### ISSUE THREAD

**Issue by acaciochinato** [jellyfin/jellyfin-plugin-discogs#6]
Hello!

I'm trying to use the plugin but after compiling, dropping the DLL into the plugins directory and restarting jellyfin the plugin shows up as NotSupported. 

I didn't understood correctly the "Release" part maybe I did something wrong in this part.

**Comment by JPVenson** [comment]
Could you please provide the jellyfin server logfiles?

**Comment by acaciochinato** [comment]
Found this:

```
[2024-02-08 09:38:16.137 -03:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/discogs/Jellyfin.Plugin.Discogs.dll". This error occurs when a plugi
n references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Threading.RateLimiting, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.RateLimiting, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

**Comment by nielsvanvelzen** [comment]
You need to add two DLL files:

- Jellyfin.Plugin.Discogs.dll
- System.Threading.RateLimiting.dll

**Comment by acaciochinato** [comment]
How do I generate the `System.Threading.RateLimiting.dll`?

**Comment by nielsvanvelzen** [comment]
Copy it from the same place you copied the plugin DLL from

**Comment by acaciochinato** [comment]
solved. Thanks!
